Add Administration View
PZ-2024/IiE_ZIELONI_2024 pull request #35
Opened 2024-06-10 19:33 UTC by michalzychowski

Dodano Administration View. Potrzeba dodać jeszcze update userów (według Kamila). I dodać tu kolorki żeby to wyglądało dobrze :)

2024-06-10 19:39 UTC, kopecklaudia reviewed
super

2024-06-11 14:26 UTC, pasierbpiotr requested changes
Popraw nazwy zmiennych i będzie git

2024-06-11 14:26 UTC, pasierbpiotr commented on CODE/project/JCoffe/src/main/java/net/zieloni/jcoffe/AdministrationController.java
> +             * @param pracownik -> drugi radio button, wybiermay go dla wpisywanego Pracownika
Nazwy zmiennych w komentarzach nie pokrywają się z tym jak później występują.

2024-06-11 14:26 UTC, pasierbpiotr commented on CODE/project/JCoffe/src/main/java/net/zieloni/jcoffe/AdministrationController.java
> +    private String rola;
Tutaj jedna zmienna po polsku co nie zgadza się z konwencją nazywania zmiennych.

2024-06-14 12:06 UTC, pasierbpiotr approved these changes

2024-06-15 12:32 UTC, merged